# Netlify Configuration for Geneva Guide Travel App
[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm run build"

# API Routes - Proxy requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets with ETag support
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"
    ETag = "true"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"
    ETag = "true"

# Don't cache API responses
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"