# Netlify Configuration for Geneva Guide Travel App
[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'No build needed for static site'"
  base = "."

# API Routes - Proxy requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://unpkg.com https://www.gstatic.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https: blob:; connect-src 'self' https://api.open-meteo.com https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://generativelanguage.googleapis.com https://*.tile.openstreetmap.org; frame-src 'none'; object-src 'none';"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(self), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# Cache static assets with ETag support
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"
    ETag = "true"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"
    ETag = "true"

# Don't cache API responses
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"